version: "3.8"
services:
  rust-rocket:
    container_name: rust-rocket
    build: ./rust-rocket
    ports:
      - 8010:8010
    deploy:
      resources:
        limits:
          memory: 1G
  go-echo:
    container_name: go-echo
    build: ./go-echo
    ports:
      - 8020:8020
    deploy:
      resources:
        limits:
          memory: 1G
  dotnet-web-api:
    container_name: dotnet-web-api
    build: ./dotnet-api
    ports:
      - 8030:8030
    deploy:
      resources:
        limits:
          memory: 1G
  dotnet-minimal-api:
    container_name: dotnet-minimal-api
    build: ./dotnet-minimal-api
    ports:
      - 8040:8040
    deploy:
      resources:
        limits:
          memory: 1G
  kotlin-ktor:
    container_name: kotlin-ktor
    build: ./kotlin-ktor
    ports:
      - 8050:8050
    deploy:
      resources:
        limits:
          memory: 1G
  kotlin-spring:
    container_name: kotlin-spring
    build: ./kotlin-spring
    ports:
      - 8060:8060
    deploy:
      resources:
        limits:
          memory: 1G
  node-nest:
    container_name: node-nest
    build: ./node-nestjs
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          memory: 1G
  node-pure:
    container_name: node-pure
    build: ./node-pure
    ports:
      - 5000:5000
    deploy:
      resources:
        limits:
          memory: 1G
  php-laravel:
    container_name: php-laravel
    build: ./php-laravel
    ports:
      - 5010:80
    deploy:
      resources:
        limits:
          memory: 1G
  svelte-ui:
    container_name: svelte-ui
    build:
      context: ./ui
      args:
        RUST_API_URL: "rust-rocket:8010"
        GO_API_URL: "go-echo:8020"
        DOTNET_API_URL: "dotnet-web-api:8030"
        DOTNET_M_API_URL: "dotnet-minimal-api:8040"
        KTOR_API_URL: "kotlin-ktor:8050"
        SPRING_API_URL: "kotlin-spring:8060"
        NODE_NEST_API_URL: "node-nest:3000"
        NODE_PURE_API_URL: "node-pure:5000"
        PHP_LARAVEL_API_URL: "php-laravel:5010"
    ports:
      - 80:80
  python-flask-api:
    container_name: python-flask-api
    build: ./python-flask-api
    ports:
      - 8070:5000
    deploy:
      resources:
        limits:
          memory: 1G
  python-django-api:
    container_name: python-djang-api
    build: ./python-django-api
    ports:
      - 8000:8000
    deploy:
      resources:
        limits:
          memory: 1G
